name: Build

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg-cache
  VCPKG_ROOT: C:\vcpkg

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Setup vcpkg
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force -Path "${{ env.VCPKG_DEFAULT_BINARY_CACHE }}"
        cd $env:VCPKG_ROOT
        .\bootstrap-vcpkg.bat
        .\vcpkg --version | Out-File "${{ github.workspace }}/vcpkg-version.txt"

    - name: Cache vcpkg
      uses: actions/cache@v5
      with:
        path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json', 'vcpkg-version.txt') }}

    - name: Configure CMake
      run: |
        cmake --preset vs-github-relwithdebinfo

    - name: Build
      run: |
        cmake --build --preset vs-github-relwithdebinfo

    - name: Install
      run: |
        cmake --install build --config RelWithDebInfo --component SKSEPlugin --prefix ${{ github.workspace }}/ReleaseBuild
        cmake --install build --config RelWithDebInfo --component components --prefix ${{ github.workspace }}/ReleaseBuild

    - name: Upload Artifact
      uses: actions/upload-artifact@v6
      with:
        name: ${{ github.event.repository.name }}
        path: ${{ github.workspace }}/ReleaseBuild